# Generated by Django 5.2.10 on 2026-01-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0023_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.conductedexam')),
            ],
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
