# Generated by Django 5.2.10 on 2026-01-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0024_examnotification_delete_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamNotification',
        ),
    ]
