# Generated by Django 5.2.10 on 2026-01-16 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0021_student_id_card_issued_student_lms_access_granted_and_more'),
        ('TrainerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('date_conducted', models.DateField(default=django.utils.timezone.now)),
                ('total_marks', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Scheduled', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.trainer')),
            ],
            options={
                'ordering': ['-date_conducted'],
            },
        ),
    ]
