# Generated by Django 5.2.10 on 2026-01-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0002_conductedexam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConductedExam',
        ),
    ]
